const mockParticipantData = {
  profile: {
    id: 1,
    name: "John Doe",
    rollNo: "CS2024001",
    email: "john.doe@student.edu",
    program: "B.Tech Computer Science",
    organization: "Tech University",
    semester: "4th",
    joinDate: "2024-01-15",
  },
  stats: {
    totalQuizzes: 12,
    attemptedQuizzes: 8,
    averageScore: 78.5,
    highestScore: 95,
    totalQuestions: 120,
    correctAnswers: 89,
    rank: 4,
    totalParticipants: 150,
  },
  upcomingQuizzes: [
    {
      id: 1,
      title: "Advanced JavaScript Concepts",
      host: "Dr. Smith",
      date: "2025-10-15",
      time: "14:00",
      duration: 60,
      totalQuestions: 20,
      difficulty: "medium",
      category: "Programming",
    },
    {
      id: 2,
      title: "Database Management Systems",
      host: "Prof. Johnson",
      date: "2025-10-18",
      time: "10:00",
      duration: 45,
      totalQuestions: 15,
      difficulty: "easy",
      category: "Database",
    },
    {
      id: 3,
      title: "Data Structures & Algorithms",
      host: "Dr. Williams",
      date: "2025-10-22",
      time: "16:00",
      duration: 90,
      totalQuestions: 25,
      difficulty: "hard",
      category: "CS Fundamentals",
    },
  ],
  attemptedQuizzes: [
    {
      id: 1,
      title: "JavaScript Basics",
      host: "Dr. Smith",
      attemptedDate: "2025-09-20",
      score: 85,
      totalQuestions: 15,
      correctAnswers: 13,
      timeTaken: "25:30",
      rank: 3,
      totalParticipants: 45,
      status: "completed",
      resultPublished: true,
    },
    {
      id: 2,
      title: "React Fundamentals",
      host: "Prof. Davis",
      attemptedDate: "2025-09-18",
      score: 72,
      totalQuestions: 12,
      correctAnswers: 9,
      timeTaken: "32:15",
      rank: 7,
      totalParticipants: 38,
      status: "completed",
      resultPublished: true,
    },
    {
      id: 3,
      title: "Web Development Quiz",
      host: "Dr. Brown",
      attemptedDate: "2025-09-15",
      score: 91,
      totalQuestions: 20,
      correctAnswers: 18,
      timeTaken: "45:20",
      rank: 1,
      totalParticipants: 62,
      status: "completed",
      resultPublished: true,
    },
    {
      id: 4,
      title: "Python Programming",
      host: "Prof. Wilson",
      attemptedDate: "2025-09-10",
      score: 68,
      totalQuestions: 18,
      correctAnswers: 12,
      timeTaken: "38:45",
      rank: 12,
      totalParticipants: 55,
      status: "completed",
      resultPublished: true,
    },
  ],
  performanceHistory: [
    { month: "Apr", score: 65 },
    { month: "May", score: 72 },
    { month: "Jun", score: 68 },
    { month: "Jul", score: 80 },
    { month: "Aug", score: 78 },
    { month: "Sep", score: 85 },
  ],
  achievements: [
    {
      id: 1,
      title: "First Quiz",
      description: "Completed your first quiz",
      icon: "🎯",
      earned: true,
    },
    {
      id: 2,
      title: "Top Performer",
      description: "Ranked #1 in a quiz",
      icon: "🏆",
      earned: true,
    },
    {
      id: 3,
      title: "Quick Learner",
      description: "Complete 5 quizzes",
      icon: "⚡",
      earned: false,
    },
    {
      id: 4,
      title: "Consistent",
      description: "Maintain 80%+ for 3 quizzes",
      icon: "📈",
      earned: false,
    },
  ],
};

export default mockParticipantData;
